name: deploy-container

on: 
  push:
    - main
  paths:
  # runs the workflow only when we make a change inside the container
    - 'packages/container/**'

defaults:
  run:
  # will run the workflow only inside the container
    working-directory: packages/container

jobs:
  build:
  # the type of virtual machine
    runs-on: ubunto-latest

    steps:
    # "uses" will load the code into the virtual machine
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn build
      # will give access to aws s3
      - uses: shinyinc/action-aws-cli@v1.2
      # will sync the files to aws s3
      - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ""